/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AAssignObjExp extends PExp
{
    private TObjIdentifier _objIdentifier_;
    private PExp _exp_;

    public AAssignObjExp()
    {
        // Constructor
    }

    public AAssignObjExp(
        @SuppressWarnings("hiding") TObjIdentifier _objIdentifier_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setObjIdentifier(_objIdentifier_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAssignObjExp(
            cloneNode(this._objIdentifier_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignObjExp(this);
    }

    public TObjIdentifier getObjIdentifier()
    {
        return this._objIdentifier_;
    }

    public void setObjIdentifier(TObjIdentifier node)
    {
        if(this._objIdentifier_ != null)
        {
            this._objIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objIdentifier_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objIdentifier_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objIdentifier_ == child)
        {
            this._objIdentifier_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objIdentifier_ == oldChild)
        {
            setObjIdentifier((TObjIdentifier) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
