/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AFractionExp extends PExp
{
    private TFraction _fraction_;

    public AFractionExp()
    {
        // Constructor
    }

    public AFractionExp(
        @SuppressWarnings("hiding") TFraction _fraction_)
    {
        // Constructor
        setFraction(_fraction_);

    }

    @Override
    public Object clone()
    {
        return new AFractionExp(
            cloneNode(this._fraction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFractionExp(this);
    }

    public TFraction getFraction()
    {
        return this._fraction_;
    }

    public void setFraction(TFraction node)
    {
        if(this._fraction_ != null)
        {
            this._fraction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fraction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fraction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fraction_ == child)
        {
            this._fraction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fraction_ == oldChild)
        {
            setFraction((TFraction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
