/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AGetterExp extends PExp
{
    private TObjIdentifier _objIdentifier_;

    public AGetterExp()
    {
        // Constructor
    }

    public AGetterExp(
        @SuppressWarnings("hiding") TObjIdentifier _objIdentifier_)
    {
        // Constructor
        setObjIdentifier(_objIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new AGetterExp(
            cloneNode(this._objIdentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGetterExp(this);
    }

    public TObjIdentifier getObjIdentifier()
    {
        return this._objIdentifier_;
    }

    public void setObjIdentifier(TObjIdentifier node)
    {
        if(this._objIdentifier_ != null)
        {
            this._objIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objIdentifier_ == child)
        {
            this._objIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objIdentifier_ == oldChild)
        {
            setObjIdentifier((TObjIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
