/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AInteger16Exp extends PExp
{
    private TInteger16 _integer16_;

    public AInteger16Exp()
    {
        // Constructor
    }

    public AInteger16Exp(
        @SuppressWarnings("hiding") TInteger16 _integer16_)
    {
        // Constructor
        setInteger16(_integer16_);

    }

    @Override
    public Object clone()
    {
        return new AInteger16Exp(
            cloneNode(this._integer16_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteger16Exp(this);
    }

    public TInteger16 getInteger16()
    {
        return this._integer16_;
    }

    public void setInteger16(TInteger16 node)
    {
        if(this._integer16_ != null)
        {
            this._integer16_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer16_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._integer16_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._integer16_ == child)
        {
            this._integer16_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._integer16_ == oldChild)
        {
            setInteger16((TInteger16) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
