/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AInteger10Exp extends PExp
{
    private TInteger10 _integer10_;

    public AInteger10Exp()
    {
        // Constructor
    }

    public AInteger10Exp(
        @SuppressWarnings("hiding") TInteger10 _integer10_)
    {
        // Constructor
        setInteger10(_integer10_);

    }

    @Override
    public Object clone()
    {
        return new AInteger10Exp(
            cloneNode(this._integer10_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteger10Exp(this);
    }

    public TInteger10 getInteger10()
    {
        return this._integer10_;
    }

    public void setInteger10(TInteger10 node)
    {
        if(this._integer10_ != null)
        {
            this._integer10_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer10_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._integer10_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._integer10_ == child)
        {
            this._integer10_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._integer10_ == oldChild)
        {
            setInteger10((TInteger10) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
