/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AInteger8Exp extends PExp
{
    private TInteger8 _integer8_;

    public AInteger8Exp()
    {
        // Constructor
    }

    public AInteger8Exp(
        @SuppressWarnings("hiding") TInteger8 _integer8_)
    {
        // Constructor
        setInteger8(_integer8_);

    }

    @Override
    public Object clone()
    {
        return new AInteger8Exp(
            cloneNode(this._integer8_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteger8Exp(this);
    }

    public TInteger8 getInteger8()
    {
        return this._integer8_;
    }

    public void setInteger8(TInteger8 node)
    {
        if(this._integer8_ != null)
        {
            this._integer8_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer8_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._integer8_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._integer8_ == child)
        {
            this._integer8_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._integer8_ == oldChild)
        {
            setInteger8((TInteger8) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
