/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.node;

import be.lmenten.utils.math.evaluator.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TFraction extends Token
{
    public TFraction(String text)
    {
        setText(text);
    }

    public TFraction(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFraction(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFraction(this);
    }
}
