/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.utils.math.evaluator.grammar.lexer;

import java.io.*;

@SuppressWarnings("serial")
public interface IPushbackReader
{
    public int read() throws IOException;
    public void unread(int c) throws IOException;
}
